export const PRODUCTS = [
  {
    id: 1,
    name: "FC 24",
    price: 200,
    discount: 60,
    image: "./images/fc_24.jpg",
    description: "",
  },
  {
    id: 2,
    name: "NBA 2K24",
    price: 90,
    discount: 50,
    image: "./images/nba2k24.jpg",
    description: "",
  },
  {
    id: 3,
    name: "Rocket League",
    price: 150,
    discount: 70,
    image: "./images/rocket_league.jpg",
    description: "",
  },
  {
    id: 4,
    name: "Fortnite",
    price: 80,
    discount: 25,
    image: "./images/fortnite.jpg",
    description: "",
  },
  {
    id: 5,
    name: "BATTLEFIELD 5",
    price: 70,
    discount: 20,
    image: "./images/battlefield5.avif",
    description: "",
  },
  {
    id: 6,
    name: "Forza Horizon 5",
    price: 110,
    discount: 10,
    image: "./images/forza5.jpeg",
    description: "",
  },
  {
    id: 7,
    name: "Grand Theft Auto 5",
    price: 150,
    discount: 60,
    image: "./images/gta5.png",
    description: "",
  },
  {
    id: 8,
    name: "Call Of Duty \ninfinite warfare",
    price: 100,
    discount: 20,
    image: "./images/cod.webp",
    description: "",
  },
  {
    id: 9,
    name: "The Sims 4",
    price: 20,
    discount: 10,
    image: "./images/sims4.png",
    description: "",
  },
];
